# Generated by Django 4.1.5 on 2023-01-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
