# Generated by Django 4.1.5 on 2023-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applyed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
